# Generated by Django 4.0.3 on 2022-03-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_position', models.CharField(max_length=100)),
                ('staff_dob', models.DateField()),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_phone', models.CharField(max_length=15)),
                ('staff_address', models.CharField(max_length=200)),
                ('staff_city', models.CharField(max_length=100)),
                ('staff_state', models.CharField(max_length=100)),
                ('staff_zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_is_occupied', models.BooleanField(default=False)),
                ('room_capacity', models.IntegerField()),
                ('hall_containing_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingApp.hall')),
                ('room_resident1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resident1', to='testingApp.student')),
                ('room_resident2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resident2', to='testingApp.student')),
                ('room_resident3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resident3', to='testingApp.student')),
                ('room_resident4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resident4', to='testingApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='hall_warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_warden', to='testingApp.staff'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_description', models.CharField(max_length=500)),
                ('complaint_date', models.DateField()),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_resolved_date', models.DateField()),
                ('action_taken_report', models.CharField(max_length=500)),
                ('complaint_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_by', to='testingApp.student')),
                ('complaint_resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_resolved_by', to='testingApp.staff')),
            ],
        ),
    ]
