# Generated by Django 4.0.3 on 2022-03-30 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testingApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('warden', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surcharges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testingApp.hall')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('warden', 'Warden'), ('hall_clerk', 'Hall Clerk'), ('hmc_chairman', 'HMC Chairman'), ('administrator', 'Administrator'), ('mess_manager', 'Mess Manager')], default='student', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('complaint_type', models.CharField(choices=[('mess', 'Mess related issues'), ('electrical', 'Electrical issues'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to=testingApp.models.get_image_upload_path)),
                ('action_taken_report', models.FileField(blank=True, null=True, upload_to=testingApp.models.get_atr_upload_path)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
